version: '3.8'
services:
  db:
    container_name: collections_db
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_NAME
      PGDATA: "/var/lib/postgresql/data"
      CLOUDINARY_CLOUD: $CLOUDINARY_CLOUD
      CLOUDINARY_API_KEY: $CLOUDINARY_API_KEY
      CLOUDINARY_API_SECRET: $CLOUDINARY_API_SECRET
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      network:
  api:
    container_name: collections_api
    build:
      context: .
      dockerfile: Collections.Api/Dockerfile
      args:
        buildnbinfo: 1
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      JWT_SECRET: $JWT_SECRET
    ports:
      - "5003:80"
    networks:
      network:
    depends_on:
      - "db"
networks:
  network:
volumes:
  db-data:
